---
title: 'Data Transformation with dyplr'
author: "Susan Davis"
date: "2023-01-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```

```{r}
filter(flights, month ==1, day == 1)
```
```{r}
jan1 <- filter(flights, month ==1, day == 1)
```

```{r}
(dec_25 <- filter(flights, month == 12, day == 25))
```
```{r}
filter(flights, month ==11 | month ==12)
```
```{r}
nov_dec <- filter(flights, month %in% c(11,12))
```

```{r}
filter(flights, !(arr_delay>120|dep_delay>120))
filter(flights, arr_delay<= 120, dep_delay<= 120)
```

```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, x >1)
```

```{r}
filter(df, is.na(x) | x > 1)
```
```{r}
arrange(flights, year, month, day)
```
```{r}
arrange(flights, desc(arr_delay))
```
```{r}
df <- tibble(x = c(5,2,NA))
arrange(df,x)
arrange(df, desc(x))
```
```{r}
select(flights,year,month, day)
```
```{r}
select(flights, year:day)
```
```{r}
select(flights, -(year:day))
```
```{r}
rename(flights, tail_num = tailnum)
```
```{r}
select(flights, time_hour, air_time, everything())
```
```{r}
flights_sml <- select(flights, year:day, ends_with('delay'), distance, air_time)
```

```{r}
mutate(flights_sml, gain = arr_delay - dep_delay, speed = distance/ air_time *60)
```
```{r}
transmute(flights,
 gain = arr_delay - dep_delay,
 hours = air_time / 60,
 gain_per_hour = gain / hours
)
```
```{r}
transmute(flights, dep_time, hour = dep_time %/% 100, minute = dep_time%%100)
```
```{r}
summarize(flights, delay = mean(dep_delay, na.rm = TRUE))
```
```{r}
by_day <- group_by(flights, year, month, day)
summarize(by_day, delay = mean(dep_delay, na.rm = TRUE))
```

```{r}
best_dest <- group_by(flights, dest)
delay <- summarize(best_dest, count = n(), 
                   dist = mean(distance, na.rm = TRUE),
                   delay = mean(arr_delay, na.rm = TRUE)
                   )
delay <- filter(delay, count > 20, dest != "HNL")
delay
```
```{r}
ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)
```
```{r}
delays <- flights %>%
  group_by(dest) %>%
  summarize(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>%
  filter(count > 20, dest != "HNL")
head(delays)
```
```{r}
flights %>%
 group_by(year, month, day) %>%
 summarize(mean = mean(dep_delay))
```

```{r}
flights %>%
 group_by(year, month, day) %>%
 summarize(mean = mean(dep_delay, na.rm = TRUE))
```

```{r}
not_cancelled <- flights %>%
 filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(mean = mean(dep_delay))
```
```{r}
delays <- not_cancelled %>%
 group_by(tailnum) %>%
 summarize(
 delay = mean(arr_delay)
 )
ggplot(data = delays, mapping = aes(x = delay)) +
 geom_freqpoly(binwidth = 10)
```

```{r}
delays <- not_cancelled %>%
 group_by(tailnum) %>%
 summarize(
 delay = mean(arr_delay, na.rm = TRUE),
 n = n()
 )
ggplot(data = delays, mapping = aes(x = n, y = delay)) +
 geom_point(alpha = 1/10)
```
```{r}
delays %>%
 filter(n > 25) %>%
 ggplot(mapping = aes(x = n, y = delay)) +
 geom_point(alpha = 1/10)
```
```{r}
# Convert to a tibble so it prints nicely
library(Lahman)
batting <- as_tibble(Lahman::Batting)
batters <- batting %>%
 group_by(playerID) %>%
 summarize(
 ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
 ab = sum(AB, na.rm = TRUE)
 )
batters %>%
 filter(ab > 100) %>%
 ggplot(mapping = aes(x = ab, y = ba)) +
 geom_point() +
 geom_smooth(se = FALSE)
#> `geom_smooth()` using method = 'gam'
```

```{r}
batters %>%
 arrange(desc(ba))
```
```{r}
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(
 # average delay:
 avg_delay1 = mean(arr_delay),
 # average positive delay:
 avg_delay2 = mean(arr_delay[arr_delay > 0])
 )
```

```{r}
not_cancelled %>%
 group_by(dest) %>%
 summarize(distance_sd = sd(distance)) %>%
 arrange(desc(distance_sd))
```
```{r}
# When do the first and last flights leave each day?
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(
 first = min(dep_time),
 last = max(dep_time))
```

```{r}
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(
 first_dep = first(dep_time),
 last_dep = last(dep_time))
```

```{r}
not_cancelled %>%
 group_by(year, month, day) %>%
 mutate(r = min_rank(desc(dep_time))) %>%
 filter(r %in% range(r))
```
```{r}
not_cancelled%>%
  group_by(dest)%>%
  summarize(carriers = n_distinct(carrier))%>%
  arrange(desc(carriers))
```

```{r}
not_cancelled %>%
 count(tailnum, wt = distance)
```
```{r}
# How many flights left before 5am? (these usually
# indicate delayed flights from the previous day)
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(n_early = sum(dep_time < 500))
```

```{r}
# What proportion of flights are delayed by more
# than an hour?
not_cancelled %>%
 group_by(year, month, day) %>%
 summarize(hour_perc = mean(arr_delay > 60))
```

```{r}
daily <- group_by(flights, year, month, day)
(per_day <- summarize(daily, flights = n()))
```

```{r}
(per_month <- summarize(per_day, flights = sum(flights)))
```

```{r}
(per_year <- summarize(per_month, flights = sum(flights)))
```

```{r}
daily %>%
 ungroup() %>% # no longer grouped by date
 summarize(flights = n()) # all flights
```

